name: Deploy Azure VM

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create env
      run: |
        echo -e "$CI_SSH_KEY" > id_rsa.txt
    - name: Deploy
      env:
        CI_DEV_SSH_USER: ${{ secrets.CI_DEV_SSH_USER }}
        CI_DEV_SSH_HOST: ${{ secrets.CI_DEV_SSH_HOST }}
      run: |
        rsync -ahrz --exclude-from '.dockerignore' -e "sudo ssh -i id_rsa.txt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ $CI_DEV_SSH_USER@$CI_DEV_SSH_HOST:shoppee-app
        sudo ssh -i id_rsa.txt -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $CI_DEV_SSH_USER@$CI_DEV_SSH_HOST "cd ai-fitness-trainer && sudo docker-compose up -d --build"